spring:
  application:
    name: ecommerce-produit-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: kemane
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

