spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: ecommerce-api-gateway
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


