spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: ecommerce-sale-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

