spring:
  application:
    name: ecommerce-vente-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: kemane
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


