apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  labels:
   app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
      - name: api-gateway-container
        image: lugar2020/api-gateway
        ports:
        - containerPort: 8082
        env:
        - name: CONFIG_SERVER
          value: "https://2f5d143d-23e8-4b55-9ff7-ee17dcad4c6f-10-244-29-79-30090.spch.r.killercoda.com"
        - name: ENV
          value: "prod"

---

apiVersion: v1
kind: Service
metadata: 
  name: gateway
  labels:
    name: api-gateway-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: api-gateway-app
