apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  labels:
   app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-container
        image: lugar2020/order-service
        ports:
        - containerPort: 8086
        env:
        - name: CONFIG_SERVER
          value: "https://2f5d143d-23e8-4b55-9ff7-ee17dcad4c6f-10-244-29-79-30090.spch.r.killercoda.com"
        - name: ENV
          value: "prod"

---

apiVersion: v1
kind: Service
metadata: 
  name: order
  labels:
    name: order-service-service
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
  selector:
    app: order-service-app
