apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  labels:
   app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-container
        image: lugar2020/user-service
        ports:
        - containerPort: 8084
        env:
        - name: CONFIG_SERVER
          value: "https://2f5d143d-23e8-4b55-9ff7-ee17dcad4c6f-10-244-29-79-30090.spch.r.killercoda.com"
        - name: ENV
          value: "prod"

---

apiVersion: v1
kind: Service
metadata: 
  name: user
  labels:
    name: user-service-service
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
  selector:
    app: user-service-app
